#!/bin/bash

# nf_conntrack is loaded on system start before sysctl executed.
echo 'nf_conntrack' >> /etc/modules

# set nf_conntrack_max.
echo 'net.netfilter.nf_conntrack_max=1000000' >> /etc/sysctl.conf
